export const theme ={
    nord:{
        dark:{
            a:"#2e3440",
            b:"#3b4252",
            c:"#434c5e",
            d:"#4c566a",
        },
        light:{
            a:"#d8dee9",
            b:"#e5e9f0",
            c:"#eceff4",},
        frost:{
            a:"#8fbcbb",
            b:"#88c0d0",
            c:"#81a1c1",
            d:"#5e81ac",
        },
        aurora:{
            a:"#bf616a",
            b:"#d08770",
            c:"#ebcb8b",
            d:"#a3be8c",
            e:"#b48ead",
        },
    }
}